### ISSUE TITLE
Extraction not working on windows for .7z file

### ISSUE THREAD

**Issue by marciomarim** [onikienko/7zip-min#14]
I've tested on mac, works fine.
On windows for the same file it gives no sign, no error, nothing happens.

Any idea?

**Comment by onikienko** [comment]
This package uses precompiled binaries of `7za` from this package - https://github.com/develar/7zip-bin  
May you try to extract this .`7z` file with `.exe` directly? https://github.com/develar/7zip-bin/tree/master/win/x64

**Comment by marciomarim** [comment]
In fact windows cant find the bin files, I had to edit 7zip-bin index.js and add 
`.replace('app.asar', 'app.asar.unpacked')`

to 
`return path.join(__dirname, "win", process.arch, "7za.exe").replace('app.asar', 'app.asar.unpacked')`

**Comment by onikienko** [comment]
Good to know.  Thanks.
So the issue not related to `7zip-min` package.
