### ISSUE TITLE
Archive entries with " = " in the filename aren't parsed correctly

### ISSUE THREAD

**Issue by emmercm** [onikienko/7zip-min#70]
These lines here are causing archive entries to be produced without a `name`: https://github.com/onikienko/7zip-min/blob/a991a5bce2a2cec46feb4f4a5f610746ea779dae/index.js#L115-L116

See an example at https://github.com/emmercm/igir/issues/249.

A file named `RoX - 6 = Six (Japan).7z` has the entries:

```
RoX - 6 = Six (Japan) (Track 1).bin
RoX - 6 = Six (Japan) (Track 2).bin
RoX - 6 = Six (Japan).cue
````

**Comment by onikienko** [comment]
Thanks for reporting @emmercm 

I will take a look
