### ISSUE TITLE
.rar support?

### ISSUE THREAD

**Issue by frogbean** [onikienko/7zip-min#97]
Extracting archive: C:\Users\emerg\Desktop\New folder\TAAnywhere\downloads\TAESC_GOLD_9_9_5.rar
ERROR: C:\Users\emerg\Desktop\New folder\TAAnywhere\downloads\TAESC_GOLD_9_9_5.rar
Can not open the file as archive

-- successfully extracts a .zip but can't seem to do the same with a .rar
Does 7zip-min support .rar?

**Comment by onikienko** [comment]
No.
https://github.com/onikienko/7zip-min#supporting-archive-formats
